version: '3'
services:

  configuration:
    image: 'configuration-service:0.0.1-SNAPSHOT'
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8080/actuator/health" ]
      timeout: 30s
      interval: 10s

  discovery:
    image: 'discovery-service:0.0.1-SNAPSHOT'
    depends_on:
        - "configuration"
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8080/actuator/health" ]
      timeout: 30s
      interval: 10s

  building:
    image: 'building-service:0.0.1-SNAPSHOT'
    depends_on:
        - "configuration"
        - "discovery"
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8080/actuator/health" ]
      timeout: 30s
      interval: 10s

  employee:
    image: 'employee-service:0.0.1-SNAPSHOT'
    depends_on:
        - "configuration"
        - "discovery"
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8080/actuator/health" ]
      timeout: 30s
      interval: 10s

  reservation:
    image: 'reservation-service:0.0.1-SNAPSHOT'
    depends_on:
        - "configuration"
        - "discovery"
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8080/actuator/health" ]
      timeout: 30s
      interval: 10s

  gateway:
    image: 'gateway-service:0.0.1-SNAPSHOT'
    depends_on:
        - "configuration"
        - "discovery"
    healthcheck:
      test: [ "CMD", "curl" ,"localhost:8080/actuator/health" ]
      timeout: 30s
      interval: 10s
    ports:
      - "8080:8080"